var novels = [
{"Name":"The Pilgrim’s Progress","Description":"A story of a man in search of truth told with the simple clarity and beauty of Bunyan’s prose make this the ultimate English classic.","Review":"7","price":200},
{"Name":"Robinson Crusoe","Description":"By the end of the 19th century, no book in English literary history had enjoyed more editions, spin-offs and translations. Crusoe’s world-famous novel is a complex literary confection, and it’s irresistible.","Review":"3","price":500},
{"Name":"Gulliver’s Travels","Description":"A satirical masterpiece that’s never been out of print, Jonathan Swift’s Gulliver’s Travels comes third in our list of the best novels written in English","Review":"6","price":100},
{"Name":"Clarissa","Description":"Clarissa is a tragic heroine, pressured by her unscrupulous nouveau-riche family to marry a wealthy man she detests, in the book that Samuel Johnson described as “the first book in the world for the knowledge it displays of the human heart.”","Review":"5","price":250},
{"Name":"Tom Jones","Description":"Tom Jones is a classic English novel that captures the spirit of its age and whose famous characters have come to represent Augustan society in all its loquacious, turbulent, comic variety.","Review":"4","price":180},
{"Name":"Emma","Description":"Jane Austen’s Emma is her masterpiece, mixing the sparkle of her early books with a deep sensibility.","Review":"3","price":200},
{"Name":"Frankenstein","Description":"Mary Shelley’s first novel has been hailed as a masterpiece of horror and the macabre.","Review":"6","price":200},
{"Name":"Nightmare Abbey ","Description":"AThe great pleasure of Nightmare Abbey, which was inspired by Thomas Love Peacock’s friendship with Shelley, lies in the delight the author takes in poking fun at the romantic movement.","Review":"8","price":150}
]